---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we've said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term "efficiency" means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of "efficiency"?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some ["a-ha" moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

Efficiency is defined as the quality of achieving the most work using a minimal amount of energy and resources. In statistical computing, efficiency includes only necessary pieces of code that cannot be revised to decrease the amount of code. This is important because it makes the code less prone to errors, and even if it does have errors, it is easier to debug. One "a-ha" moment I had about efficiency was that for Lab 5 (Finding the Suspects), I didn't have to have a separate pipeline for each inner join, and instead, I could have made it into a single pipeline by piping the inner joins into the following inner join.
